name = "10xdevscards"
compatibility_date = "2024-05-02"

[build]
command = "npm run build"
upload.format = "directory"

[site]
bucket = "./dist"

[pages]
pages_build_output_dir = "./dist"

[env.production]
workers_dev = true 